### PR TITLE
fix V-DOGE-VUL-010

### LINKED ISSUE #48: Fix V-DOGE-VUL-010
MustDecodeHex(input) could cause process panic. input content come from outer. main process should not panic handle the msg came from outer. Throw the error and log the info in stead of panic.

### PR DESCRIPTION
**Pull request by abrahamcruise321**
# Description

MustDecodeHex(input) could cause process panic. input content come from outer. main process should not panic handle the msg came from outer. Throw the error and log the info in stead of panic.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [x] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### CODE REVIEW

File: helper/hex/hex.go [hunk 1]
```diff
@@ -45,13 +45,13 @@ func DecodeHex(str string) ([]byte, error) {
 }
 
 // MustDecodeHex type-checks and converts a hex string to a byte array
-func MustDecodeHex(str string) []byte {
+func MustDecodeHex(str string) ([]byte, error) {
```
Comment (DarianShawn) [inline helper/hex/hex.go]: Could we rename it to `DecodeHex`?
The `Must` would panic, it is a golang convention.

**Review by DarianShawn — COMMENTED** [review]
Awesome work, 🙌
We only need a little typo work.

File: helper/hex/hex.go (hunk 1 above)
Comment (abrahamcruise321) [reply helper/hex/hex.go]: keep with edge.

Comment (abrahamcruise321) [reply helper/hex/hex.go]: replace MustDecodeHex  with DecodeHex

**Review by DarianShawn — APPROVED** [review]
LGTM. 💯
