### PR TITLE
daemon for jury

### LINKED ISSUE #12: Daemon for jury.
Daemon read private key input when started. Restart dogechain when crashed, protect anyone to get the private key on the server. So the private key is not left in the file, or can’t be got by the process id.

### PR DESCRIPTION
**Pull request by abrahamcruise321**
# Description

Daemon read private key input when started. Restart dogechain when crashed, protect anyone to get the private key on the server. So the private key is not left in the file, or can’t be got by the process id.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### CODE REVIEW

**Comment by abrahamcruise321** [comment]
I have read the CLA Document and I hereby sign the CLA

File: Makefile [hunk 1]
```diff
@@ -21,7 +21,7 @@ build:
 	$(eval LATEST_VERSION = $(shell git describe --tags --abbrev=0))
 	$(eval COMMIT_HASH = $(shell git rev-parse --short HEAD))
 	$(eval DATE = $(shell date +'%Y-%m-%d_%T'))
-	go build -ldflags="-X 'github.com/dogechain-lab/jury/versioning.Version=$(LATEST_VERSION)+$(COMMIT_HASH)+$(DATE)'" main.go
+	go build -ldflags="-X 'github.com/dogechain-lab/jury/versioning.Version=$(LATEST_VERSION)+$(COMMIT_HASH)+$(DATE)'" -o bin/jury main.go
```
Comment (DarianShawn) [inline Makefile]: Would be better to give another PR.

File: command/server/server.go [hunk 2]
```diff
@@ -238,6 +249,45 @@ func isConfigFileSpecified(cmd *cobra.Command) bool {
...
+			if err != nil {
+				log.Println("Child process ", os.Getpid(), " read pipe data err: ", err)
+			} else {
+				log.Println("Child process ", os.Getpid(), " read pipe data: ", len(string(data)))
+				params.validatorKey = string(data)
+			}
+		}
+
+		// Create a daemon object
+		logFile := "daemon.log"
```
Comment (DarianShawn) [inline command/server/server.go]: Could we extract out the constant?

File: command/server/server.go [hunk 3]
```diff
@@ -238,6 +249,45 @@ func isConfigFileSpecified(cmd *cobra.Command) bool {
...
+		newDaemon := daemon.NewDaemon(logFile)
+		newDaemon.MaxCount = 5
```
Comment (DarianShawn) [inline command/server/server.go]: Could we extract out the constant?

File: command/server/server.go [hunk 4]
```diff
@@ -238,6 +249,45 @@ func isConfigFileSpecified(cmd *cobra.Command) bool {
 func runCommand(cmd *cobra.Command, _ []string) {
 	outputter := command.InitializeOutputter(cmd)
 
+	log.Println("Main process run isDaemon:", params.isDaemon)
+
+	// Launch daemons
+	if params.isDaemon {
+		// First time, err is not empty
+		_, err := strconv.Atoi(os.Getenv(daemon.EnvName))
```
Comment (DarianShawn) [inline command/server/server.go]: Why not use `len()` for environment variable condition judging?

File: helper/daemon/daemon.go [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+// Turn the the main program into background running (start a child process, and then exit)
+// logFile - If it is not empty, the standard output and error output of the child process will be recorded in this file
+// isExit - Whether to exit the main program directly after the child process started.
+//          If false, the main program returns * OS Process, the child process returns nil.
+//          It needs to be handled by the caller.
+func Background(logFile string, priKey string, isExit bool) (*exec.Cmd, error) {
+	// Check whether the child process or the parent process
+	runIdx++
+
+	envIdx, err := strconv.Atoi(os.Getenv(EnvName))
```
Comment (DarianShawn) [inline helper/daemon/daemon.go]: `len()` condition would be better understood.

File: command/server/server.go [hunk 6]
```diff
@@ -238,6 +249,45 @@ func isConfigFileSpecified(cmd *cobra.Command) bool {
...
+		newDaemon.MaxCount = 5
+		newDaemon.ValidatorKey = params.validatorKey
+
+		// Execute daemon mode
+		newDaemon.Run()
+
+		//当 *d = true 时以下代码只有最终子进程会执行, 主进程和守护进程都不会执行
+		log.Println("Child process ", os.Getpid(), "start...")
+		log.Println("Child process ", os.Getpid(), "isDaemon: ", params.isDaemon)
+		log.Println("Child process ", os.Getpid(), "ValidatorKey: ", len(params.validatorKey))
```
Comment (DarianShawn) [inline command/server/server.go]: Better not print out this private key, since it is logging in file.
Could print out the public key, for user confirmation.

File: command/server/server.go [hunk 7]
```diff
@@ -238,6 +249,45 @@ func isConfigFileSpecified(cmd *cobra.Command) bool {
...
+		// First time, err is not empty
+		_, err := strconv.Atoi(os.Getenv(daemon.EnvName))
+		if err != nil {
+			input, err := gopass.GetPasswdPrompt("Enter ValidatorKey:", true, os.Stdin, os.Stdout)
+			if err != nil {
+				log.Println("Parent process ", os.Getpid(), " passwd prompt err:", err)
+			}
+
+			params.validatorKey = string(input)
+			log.Println("Parent process ", os.Getpid(), " passwd prompt, ValidatorKey:", len(params.validatorKey))
```
Comment (DarianShawn) [inline command/server/server.go]: Do not print out private key to the log file, use public key instead.

File: command/server/server.go (hunk 6 above)
Comment (DarianShawn) [inline command/server/server.go]: Do not print out private key to the log file, use public key instead.

**Review by DarianShawn — COMMENTED** [review]
Thanks for the nice solution.
I've leave some suggestions for you.

File: command/server/server.go (hunk 7 above)
Comment (abrahamcruise321) [reply command/server/server.go]: not  private key, length of  private key.

File: command/server/server.go (hunk 2 above)
Comment (abrahamcruise321) [reply command/server/server.go]: fix

File: command/server/server.go (hunk 7 above)
Comment (DarianShawn) [reply command/server/server.go]: 🫢 My fault.
The `ValidatorKey` key in the log is a little confusing.

File: command/server/server.go (hunk 6 above)
Comment (DarianShawn) [reply command/server/server.go]: 😅 My mistake.
The `validatorKey` would only print out the length.

Comment (DarianShawn) [reply command/server/server.go]: My mistake. Resolved.

File: command/server/server.go (hunk 3 above)
Comment (abrahamcruise321) [reply command/server/server.go]: fix

File: command/server/server.go (hunk 4 above)
Comment (abrahamcruise321) [reply command/server/server.go]: fix

File: helper/daemon/daemon.go (hunk 5 above)
Comment (abrahamcruise321) [reply helper/daemon/daemon.go]: envIdx has to assgn value, no need use more variable.

File: command/server/server.go (hunk 4 above)
Comment (DarianShawn) [reply command/server/server.go]: OK. Got it.

**Review by DarianShawn — APPROVED** [review]
LGTM. 💯
Thanks for this incredible feature.
You're ready to merge now.
